# Site settings
title: The Anuyog Institute
email: theanuyoginstitute@gmail.com
description: >
  Welcome to our transformative community of dedicated scientists and scholars on a quest to merge the deep knowledge from the Vedas with cutting-edge scientific advancements. 
  Our primary aim is to illuminate the perfect path toward a happy life, while effortlessly evading diseases and suffering.
baseurl: "" 
#url: "http://localhost:4000" 
url: https://jprags2023.github.io 
#repository: 'egeis/jekyll-modern-business'
#repository: 'jprags2023'
repository: ''
category_dir: 'blog'

# Theme Settings
modern:
  blog-index-style: '1'
  portfolio-index-style: '1'
  organization: 'The ANUYOG INSTITUTE'
  defaults: 
    blog:
      frontimagesrc: 'http://placehold.it/900x300' 
    portfolio:
      frontimagesrc: 'http://placehold.it/700x300'

# Markdown Settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
highlighter: rouge

# Outputting
permalink: /:categories/:title/

# Build Settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  - octopress  
  - octopress-paginate
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - octopress
  - octopress-paginate
include:
  - .htaccess
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - CHANGELOG.md
  - .sass-cache
  - .asset-cache
  - .bundle
  - vendor
  - log
encoding: "utf-8"

# Collection Settings
collections:
   posts:
     permalink: /blog/:categories/:title.html
     output: true
   projects:
     output: true
     permalink: /portfolio/:categories/:title.html
   members:
     output: false
   customers:
     output: false   

# Octopress settings
post_ext: md
page_ext: html
paginate:
  per_page: 10 
  limit: 5   
  title_suffix: " - page :num"
  reversed: false  

# Default templates for posts and pages
post_layout: post
page_layout: default

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft	 
